# Data set exploration

- Binary classification problem
In this project, I'm gonna use the Diabetes dataset originally comes from the UCI machine learning repository. The data consists of over 100000 hospital admissions from patients with diabetes from 130 US hospitals between 1999-2008

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

In [4]:
df = pd.read_csv('diabetic_data.csv')
print('Number of samples: ', len(df))
df.info()

Number of samples:  101766
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766

Overall, the columns are in various types: identification columns, numerical columns, categorical (free-text) columns.

In [5]:
df.head()

encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?   
1        149190     55629189        Caucasian  Female  [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?   
3        500364     82442376        Caucasian    Male  [30-40)      ?   
4         16680     42519267        Caucasian    Male  [40-50)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  

[5 rows x 50 columns]

- There is some missing data that are represented with ?. We will deal with this in the feature engineering section
- The most important column here is readmitted, which tell us if a patient was hospitalized within 30 days, greater than 30 days or not readmitted

In [6]:
#count the number of rows for each type
df.groupby('readmitted').size()

readmitted
<30    11357
>30    35545
NO     54864
dtype: int64

Another column that is important is discharge_disposition_id which tells us where the patient went after hospitalization.

In [7]:
df.groupby('discharge_disposition_id').size()

discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
dtype: int64

By looking at IDs_mapping.csv, we can see that 11, 13, 14, 19, 20, 21 are related to death or hospice -> remove

In [9]:
df = df.loc[~df.discharge_disposition_id.isin([11,13,14,19,20,21])]

This step we are preparing the output for our binary classification problem. We will try to predict if a patient is likely to be re-admitted within 30 days of discharge

In [10]:
df['OUTPUT_LABEL'] = (df.readmitted == '<30').astype('int')


Define a function to calculate the prevalence of population that is readmitted with 30 days

In [16]:
def calcPrevalence(y_actual):
    return (sum(y_actual)/len(y_actual))

print('Prevalence: %.3f'%calcPrevalence(df['OUTPUT_LABEL'].values))

Prevalence: 0.114


In a similar fashion with other medical data, this represented an imbalanced classification problem so we will address that below

In [17]:
print('Number of columns:', len(df.columns))

Number of columns: 51


In [19]:
df[list(df.columns)[:10]].head()

citoglipton insulin glyburide-metformin glipizide-metformin  \
0          No      No                  No                  No   
1          No      Up                  No                  No   
2          No      No                  No                  No   
3          No      Up                  No                  No   
4          No  Steady                  No                  No   

  glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone  \
0                       No                      No                     No   
1                       No                      No                     No   
2                       No                      No                     No   
3                       No                      No                     No   
4                       No                      No                     No   

  change diabetesMed readmitted  OUTPUT_LABEL  
0     No          No         NO             0  
1     Ch         Yes        >30             0  
2     No         Yes         NO             0  
3     Ch         Yes         NO             0  
4     Ch         Yes         NO             0

In [20]:
df[list(df.columns)[20:30]].head()

diag_3  number_diagnoses max_glu_serum A1Cresult metformin repaglinide  \
0      ?                 1          None      None        No          No   
1    255                 9          None      None        No          No   
2    V27                 6          None      None        No          No   
3    403                 7          None      None        No          No   
4    250                 5          None      None        No          No   

  nateglinide chlorpropamide glimepiride acetohexamide  
0          No             No          No            No  
1          No             No          No            No  
2          No             No          No            No  
3          No             No          No            No  
4          No             No          No            No

In [21]:
df[list(df.columns)[40:]].head()

citoglipton insulin glyburide-metformin glipizide-metformin  \
0          No      No                  No                  No   
1          No      Up                  No                  No   
2          No      No                  No                  No   
3          No      Up                  No                  No   
4          No  Steady                  No                  No   

  glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone  \
0                       No                      No                     No   
1                       No                      No                     No   
2                       No                      No                     No   
3                       No                      No                     No   
4                       No                      No                     No   

  change diabetesMed readmitted  OUTPUT_LABEL  
0     No          No         NO             0  
1     Ch         Yes        >30             0  
2     No         Yes         NO             0  
3     Ch         Yes         NO             0  
4     Ch         Yes         NO             0

From this, we see that there are a lot of categorical (non-numeric) variables. Note that the variables with _id are also categorical and you can see what the ids refer to with the IDs_mapping.csv. Let's take a look at the unique values for each column.

In [23]:
for c in list(df.columns):
    n = df[c].unique()
    if len(n) < 30:
        print(c)
        print(n)
    else:
        print(c + ': ' + str(len(n))+ ' unique values')

encounter_id: 99343 unique values
patient_nbr: 69990 unique values
race
['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']
gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
weight
['?' '[75-100)' '[50-75)' '[0-25)' '[100-125)' '[25-50)' '[125-150)'
 '[175-200)' '[150-175)' '>200']
admission_type_id
[6 1 2 3 4 5 8 7]
discharge_disposition_id
[25  1  3  6  2  5  7 10  4 18  8 12 16 17 22 23  9 15 24 28 27]
admission_source_id
[ 1  7  2  4  5 20  6  3 17  8  9 14 10 22 11 25 13]
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
payer_code
['?' 'MC' 'MD' 'HM' 'UN' 'BC' 'SP' 'CP' 'SI' 'DM' 'CM' 'CH' 'PO' 'WC' 'OT'
 'OG' 'MP' 'FR']
medical_specialty: 73 unique values
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient
[ 0  1  2  3  6 


From analysis of the columns, we can see there are a mix of categorical (non-numeric) and numerical data. A few things to point out,

- encounter_id and patient_nbr: these are just identifiers and not useful variables
- age and weight: are categorical in this data set
- admission_type_id,discharge_disposition_id,admission_source_id: are numerical here, but are IDs (see IDs_mapping). They should be considered categorical. 
- examide and citoglipton only have 1 value, so we will not use these variables
- diag1, diag2, diag3 - are categorical and have a lot of values. We will not use these as part of this project, but you could group these ICD codes to reduce the dimension. We will use number_diagnoses to capture some of this information. 
- medical_speciality - has many categorical variables, so we should consider this when making features. 



# Feature engineering


In this section, we will create features for our predictive model.

In [24]:
# replace ? with nan
df = df.replace('?',np.nan)


# Numerical Features

The easiest type of features to use is numerical features. These features do not need any modification. The columns that are numerical that we will use are shown below


In [25]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']

df[cols_num].isnull().sum()

time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
dtype: int64

# Categorical Features
Definition: non-numeric data such as race and gender. To turn this non-numerical data into variables, the simplest thing is to use a technique called one-hot encoding, which will be explained below

In [27]:
cols_cat = ['race', 'gender', 
       'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed','payer_code']
df[cols_cat].isnull().sum()

race                         2234
gender                          0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
payer_code                  39398
dtype: int64

In [28]:
df['race'] = df['race'].fillna('UNK')
df['payer_code'] = df['payer_code'].fillna('UNK')
df['medical_specialty'] = df['medical_specialty'].fillna('UNK')

Let's investigate medical specialty before we begin.

In [29]:
print('Number medical specialty:', df.medical_specialty.nunique())
df.groupby('medical_specialty').size().sort_values(ascending = False)

Number medical specialty: 73


medical_specialty
UNK                                 48616
InternalMedicine                    14237
Emergency/Trauma                     7419
Family/GeneralPractice               7252
Cardiology                           5279
                                    ...  
Surgery-PlasticwithinHeadandNeck        1
Dermatology                             1
Proctology                              1
Psychiatry-Addictive                    1
Speech                                  1
Length: 73, dtype: int64

Most of them are unknown and the count drops off pretty quickly. Adding 73 new variables is a waste. As an alternative, we can create a new variable that only has 11 options

In [31]:
top10 = ['UNK','InternalMedicine','Emergency/Trauma',\
          'Family/GeneralPractice', 'Cardiology','Surgery-General' ,\
          'Nephrology','Orthopedics',\
          'Orthopedics-Reconstructive','Radiologist']

# make a new column with duplicated data
df['med_spec'] = df['medical_specialty'].copy()

# replace all specialties not in top 10 with 'Other' category
df.loc[~df.med_spec.isin(top10), 'med_spec'] = 'Other'
df.groupby('med_spec').size()

med_spec
Cardiology                     5279
Emergency/Trauma               7419
Family/GeneralPractice         7252
InternalMedicine              14237
Nephrology                     1539
Orthopedics                    1392
Orthopedics-Reconstructive     1230
Other                          8199
Radiologist                    1121
Surgery-General                3059
UNK                           48616
dtype: int64

function to convert categorical features to numbers is get_dummies in pandas, but it does not work on numerical data. To trick get_dummies, we can convert the numerical data into strings

In [32]:
cols_cat_num = ['admission_type_id', 'discharge_disposition_id', 'admission_source_id']
df[cols_cat_num] = df[cols_cat_num].astype('str')

In [34]:
df_cat = pd.get_dummies(df[cols_cat + cols_cat_num + ['med_spec']], drop_first=True)
df_cat.head()

race_Asian  race_Caucasian  race_Hispanic  race_Other  race_UNK  \
0           0               1              0           0         0   
1           0               1              0           0         0   
2           0               0              0           0         0   
3           0               1              0           0         0   
4           0               1              0           0         0   

   gender_Male  gender_Unknown/Invalid  max_glu_serum_>300  \
0            0                       0                   0   
1            0                       0                   0   
2            0                       0                   0   
3            1                       0                   0   
4            1                       0                   0   

   max_glu_serum_None  max_glu_serum_Norm  ...  med_spec_Emergency/Trauma  \
0                   1                   0  ...                          0   
1                   1                   0  ...                          0   
2                   1                   0  ...                          0   
3                   1                   0  ...                          0   
4                   1                   0  ...                          0   

   med_spec_Family/GeneralPractice  med_spec_InternalMedicine  \
0                                0                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   

   med_spec_Nephrology  med_spec_Orthopedics  \
0                    0                     0   
1                    0                     0   
2                    0                     0   
3                    0                     0   
4                    0                     0   

   med_spec_Orthopedics-Reconstructive  med_spec_Other  med_spec_Radiologist  \
0                                    0               1                     0   
1                                    0               0                     0   
2                                    0               0                     0   
3                                    0               0                     0   
4                                    0               0                     0   

   med_spec_Surgery-General  med_spec_UNK  
0                         0             0  
1                         0             1  
2                         0             1  
3                         0             1  
4                         0             1  

[5 rows x 133 columns]